### ISSUE TITLE
mkdocs-material social icon error

### ISSUE THREAD

**Issue by shortpoet** [adrianhall/develop-mobile-apps-with-csharp-and-azure#104]
Thank you for this awesome free book, can't wait to get through it!!

I don't have any experience with mkdocs so I'm sorry I can't be more helpful up front.  I got a templatenotfound error and found [this issue](https://github.com/squidfunk/mkdocs-material/issues/1469) that might explain it.  I was able to get the docs to build by commenting out the social extras for now.
![image](https://user-images.githubusercontent.com/28075512/87572125-b1df1980-c690-11ea-8720-de15a600853d.png)

**Comment by adrianhall** [comment]
Thanks for the report.  I'm re-doing the book, so I'll fix it in the new edition.
