### ISSUE TITLE
Chapter2 - Custom Authentication

### ISSUE THREAD

**Issue by orcundeniz** [adrianhall/develop-mobile-apps-with-csharp-and-azure#18]
I am  working  on chapter 2 -  custom authentication on your book [there](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/) , I did everything correctly, but at the end of the mobile client part, When I clicked the "enter the app " button  with username adrian and pw supersecret  , I am getting "[0:] [ExecuteLoginCommand] Error = Object reference not set to an instance of an object." and notting happen. 
I think it stuck  "await cloudService.LoginAsync(User);"  on method ExecuteLoginCommand() at EntryPageViewModel.cs

When I add following lines, it works

                MobileServiceClient client = new MobileServiceClient("https://beamore2.azurewebsites.net");
                await client.LoginAsync("custom", JObject.FromObject(User));
               // var cloudService = ServiceLocator.Instance.Resolve<ICloudService>();
               //await cloudService.LoginAsync(User);

There isn't any problem for post request.I tried with Postman as you said and it works.
In chapter 2 - custom authentication, There is a class that you are not talking about  in EntryPageViewModel.cs. ServiceLocater. I added TaskList.Helper folder and ServiceLocater.cs from your Chapter 2 folder on github.

**Comment by ericbrunner** [comment]
@orcundeniz I am a user like you and Adrians book is my current ZUMO bible. I guess the `cloudService ` variable is null. Please check that with stepping through your code.

      
       sync Task ExecuteLoginCommand()
        {
            if (IsBusy)
                return;
            IsBusy = true;

            try
            {
                var **cloudService** = ServiceLocator.Instance.Resolve<ICloudService>();
                await cloudService.LoginAsync(User);
                Application.Current.MainPage = new NavigationPage(new Pages.TaskList());
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"[ExecuteLoginCommand] Error = {ex.Message}");
            }
            finally
            {
                IsBusy = false;
            }
        }
```

**Comment by adrianhall** [comment]
@ericbrunner is correct here.  A null reference is generally because you have not set something correctly.  All the demo projects are on GitHub and are stored only when they are working.  I also test and update them for each new release of the Azure Mobile Apps SDK.  

I suggest setting a breakpoint on the method that contains the exception and stepping through the code to determine what variable is not set.  As @ericbrunner suggested, it is likely the cloudService, but could be anything.
