### ISSUE TITLE
Chapter 1 - DeleteItemAsync - Typos

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#2]
`Chapter 1 / Your First App - PC Edition / The Mobile Client / AzureCloudTable<T>
`

ICloud interface is correct, but the implementation has an incorrect signature as it returns a Task<T>.  Note the method doesn't return anything.

Ditto for the sample lambda instructions in the inset note.

**Comment by adrianhall** [comment]
Guess I had a few cut-and-paste special errors.  The code was correct, but I tweaked after I cut and paste.  Thanks for the report!
