### ISSUE TITLE
Custom Authentication

### ISSUE THREAD

**Issue by arrebagrove** [adrianhall/develop-mobile-apps-with-csharp-and-azure#21]
Hello, please how do I go about this?

I get this exception {"Object reference not set to an instance of an object."} when I attempt to login on the client side like this:
client.LoginAsync(provider, JObject.FromObject(loginRequest)). as for the server side, I followed the example set out in the Azure documentation and also chapter 2. here is my custom authentication api: public IHttpActionResult Post([FromBody] JObject assertion)

Just to add, when I use Postman to authenticate https://xxxx.azurewebsites.net/.auth/login/custom, it works great.

{"username": "EbukaE","password": "1234"}

**Comment by adrianhall** [comment]
Standard debugging here.  Set a breakpoint and examine client, provider, loginRequest.  The exception is because the variables you are using are not set.
