### ISSUE TITLE
Misleading Text in Chapter 5 - Push Notifications - Concepts

### ISSUE THREAD

**Issue by ericbrunner** [adrianhall/develop-mobile-apps-with-csharp-and-azure#23]
Hi Adrian,

That Text doesn't match to the screenshot displayed above that text:

> Here, I have three client requested tags and **two automatically generated tags that are only added when authenticated**. Let's suppose that the mobile client requested [ topic:World topic:Sports ] and the mobile client was authenticated as username user@foo.com. With this configuration, the user would be registered for the following tags:
topic:Sports
auto:user@foo.com
The topic:Politics and topic:News tags would not be added because the user did not request them. The topic:World tag would not be added because it is not in the whitelist of allowed client requested tags.

I mean that subtext:  

`two automatically generated tags that are only added when authenticated`

There is only 1 automatically added Tag displayed in the screenshot.

best
Eric

**Comment by adrianhall** [comment]
Fixed in a796c6a
