### ISSUE TITLE
Feature Request: Chapter 5  - How-to do Push Notification Installation with CustomAuthController

### ISSUE THREAD

**Issue by ericbrunner** [adrianhall/develop-mobile-apps-with-csharp-and-azure#24]
Hi Adrian,

All I currently read in Chapter 5 is about push registration installation with non custom authentication providers. It would be great if you could add a section which discribes the way to setup the push registration installation for Android, iOS with a CustomAuthController in the mobile backend.

Especially how to add so called **Automatically added Tags** in the Azure portal for that CustomAuthController, because that pattern as discribed (I guess):

Link: [Provider Claims](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter5/concepts/)
> The $(provider.claim) format is used in automatically added tags to add claims from the authenticated user into the notification hub installation. You can use any claim that is returned by the /.auth/me endpoint. The standard identifiers are:
> $(provider.emailaddress)
> $(provider.identityprovider)
> $(provider.name)
> Replace provider with the provider name (facebook, google, microsoftaccount, twitter or aad). The list of claims that are available is different for each provider and additional claims may be available. It is possible to configure Azure AD to return groups, for example. Check the output of the /.auth/me endpoint to determine which claims are available.

does only work with that non custom auth providers.

best
Eric

**Comment by adrianhall** [comment]
It only works with built-in providers.  I'll make that clear in the content.  CUstom Auth - there is no concept of claims in App Service.

**Comment by ericbrunner** [comment]
@adrianhall Not good. I still notced that the _UserId is set to the MD5 hashcode of the NameIdentifier. So my _UserId has not the IMEI I set in the CustomAuthController as JWT.Sub. As a workaround I have the idea to send my targeted push messages to the ZUMO Client InstallationId like:

`$InstallationId:{073cc549-e4d7-4069-bfae-7ad5e87818c8}`

Is that ok?

**Comment by adrianhall** [comment]
You've got expected activity.  Using the Installation Id is a good idea if you know it.  You will have to specify the tags per chapter 5 of http://aka.ms/zumobook for custom auth.

**Comment by ericbrunner** [comment]
LET US TALK ONESTLY. Do you really mean it is intended that the Jwt.Sub (NameIdentifier) is hashed with MD5 encoding? IF SO, how to send targeted push to individual client?
