### ISSUE TITLE
Margins on some pages

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#26]
Looks like after the table of contents was added in the right margin, some pages don't seem to wrap the center column properly.  The first page does, though.

The result is a center section that has a scroll bar at the bottom.  I found this in the authentication section.

Little hard to read an otherwise great piece of work.

here: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/backend/

**Comment by adrianhall** [comment]
Thanks for the report - I'm trying out a new template.  I'll figure this out.

**Comment by nhwilly** [comment]
Hey, I  just noticed that the occurs when a reader expands the window to show all three sections.  But, if you shrink the browser so that the left column disappears, then the center section no longer scrolls and is displayed correctly.  HTH.

**Comment by adrianhall** [comment]
Updated mkdocs-material to v1.0.3 which looks to have solved this.  Basically, https://github.com/squidfunk/mkdocs-material needs to fix their template since I rely on that.  Please re-open if you find another instance of this.
