### ISSUE TITLE
Chapter 2 - ServiceLocator returns null because it's not initialized

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#28]
In the book sample, the line below is added to the `ExecuteLoginCommand()`

`        var cloudService = ServiceLocator.Instance.Resolve<ICloudService>();
`

But the line below needs to be added to App.cs before it will work:

`            ServiceLocator.Instance.Add<ICloudService, AzureCloudService>();
`

And no instructions are provided for that.  Maybe it happens later.

I figured that's what was happening, but I'm walking through building the code by hand, rather than copying it from the repo.

**Comment by nhwilly** [comment]
Hmmm.  I see the problem.  At this point in the book, if I change `App.cs` to use the `ServiceLocator`, the tables break.  Oh, well.  Just FYI, then.

**Comment by adrianhall** [comment]
I've missed a step - thanks!  Can you please copy-and-paste the nearest anchor into this issue, and I will fix

**Comment by nhwilly** [comment]
Sorry, I'm a twit.  Do you mean an HTML anchor (if so, how do I get those to show in Edge) or do you just mean an unique searchable string?

Or am I still missing something?

**Comment by nhwilly** [comment]
In addition, 

`TaskDetailViewModel`
- `TaskDetailViewModel(TodoItem item = null)`:

 - add: `ICloudService cloudService = ServiceLocator.Instance.Resolve<ICloudService>();`
 - add: `Table = ServiceLocator.Instance.Resolve<ICloudService>().GetTable<TodoItem>();`

`TaskListViewModel`
- `Task ExecuteRefreshCommand()`

- add: `var table = ServiceLocator.Instance.Resolve<ICloudService>().GetTable<TodoItem>();`

`App`
- `App()`

- add: `ServiceLocator.Instance.Add<ICloudService, AzureCloudService>();`

You may want to revisit the section of the viewmodel code in its entirety.  Turns out your repo code has had a few more changes - mostly style, I believe.  I just adopted the techniques from your repo code.  Seemed easier to read to me.

Thanks again for this book.  You nicely anticipate almost every question I have.  My questions are pretty standard, but having an author answer them almost at the same time as they are coming into my head is rare.

**Comment by adrianhall** [comment]
I meant a HTML anchor.  If you roll over the H2/H3 type headings, it will appear.  You can also just click on the headings to get it in the address bar.

**Comment by nhwilly** [comment]
Well, here's the anchor: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/enterprise/#adding-authentication-to-a-mobile-client

But in this section you never really return to App, TaskDetailViewModel or TaskListViewModel which is where the changes needs to be made.

**Comment by adrianhall** [comment]
Fixed in 7db4c3f
