### ISSUE TITLE
Possible helpful note...

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#29]
OK, I found an answer to my problem on SO, but here's a possible additional warning you might pass along to others like me.

In Chapter One, you create the `AzureCloudService` class.  If, like me, you want to make sure you've got the app URL right, you go to the App Service page for your App and use the copy button on the Overview page to copy the URL of the app.

But, you **don't** get the HTTPS, you only get HTTP.

And much later... that throws an error in `AzureCloudTable`:

`Cannot populate JSON array onto type 'TaskList.Models.TodoItem'. Path '', line 1, position 1.`  

You can retrieve the items, even delete them, but when you try to create or save them, no dice.

So naturally, the novice - me again - chases in forty directions looking at the code.

Just trying to help here...

**Comment by adrianhall** [comment]
Totally agree - I think I'll file a bug in Azure App Service as well :-)  Another note that is well worthwhile.

**Comment by adrianhall** [comment]
Fixed in 3eee744
