### ISSUE TITLE
Chapter 1 - ICloudTable<T> - Typos

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#3]
`Chapter 1 / Your First App - PC Edition / The Mobile Client / ICloudTable<T>`

`Task<ICollection<T>> ReadAllItemsAsync() where T : TableData; `

Compiler doesn't like the constraint on non-generic declarations.

Seems to work if I do this `Task<ICollection<T>> ReadAllItemsAsync() ;`

**Comment by adrianhall** [comment]
This is wierd insofar as I cut and paste all examples from working code.  Will investigate.

**Comment by adrianhall** [comment]
Well, the code that is alongside the text was correct - it was just a bug in the text.  Thanks for the report!
