### ISSUE TITLE
Using ADAL with B2C instead of MSAL

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#30]
At this link in the Best Practices section of Authentication you suggest using ADAL:

https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/bestpractices/#use-the-client-sdk-provided-by-the-identity-provider

But the SO post below by Vittorio states that ADAL will not work and that MSAL is the only one that will work against B2C:

http://stackoverflow.com/questions/40046598/msal-or-adal-library-for-use-with-azure-ad-b2c-and-xamarin

Naturally MSAL and B2C won't work together against the social providers.

**Comment by adrianhall** [comment]
I need to have words with Vittorio since experimentation does not bear out his assertion.  The reality is that ADAL is being phased out in favor of MSAL.  Until we get done with the phasing (and subsequent support for the v2 endpoints in Azure App Service), we'll have this confusion.

I'll add a note to this effect in the book so stay tuned.

**Comment by nhwilly** [comment]
Looking forward to that as I'm working to get the token directly from the IDP (in this case B2C) and call a custom endpoint.  Using the client.LoginAsync and a server approach, it works but it seems like a lot of hops to get it done.

**Comment by adrianhall** [comment]
After discussing with various people inside MSFT, we cannot support AAD B2C in a client-flow right now.

**Comment by adrianhall** [comment]
Fixed in 669beae

**Comment by khilscher** [comment]
Hi Adrian, to clarify...if using Xamarin.Forms + MSAL + Mobile App Client SDK in the mobile app and Mobile App/App Service on the backend, with App Service Authentication configured to AAD B2C (with only 'local accounts' enabled), is this client flow supported? If not, what's Azure product is holding us back from supporting this flow?

**Comment by adrianhall** [comment]
@khilscher It's a combination of things.  AAD B2C uses OAuth v2 endpoints, and MSAL uses those.  However, OAuth v2 isn't handled by App Service Auth, so we can't validate the tokens that it generates.  Since App Service Auth doesn't support AAD B2C officially, we are left with (a) validating the tokens ourselves (a la Auth0 case) or (b) using server-flow only.

**Comment by nhwilly** [comment]
@khilscher   This probably isn't helping, but I was able to use B2C and MSAL to get a token back to the client that I then sent to a Mobile App `custom` authentication endpoint and extract the claims I needed.  I just couldn't validate the claim.  I presume it's because I needed the signing key, which I don't believe I have.

I found this link:

https://social.msdn.microsoft.com/Forums/en-US/893a6142-1508-4aa2-9da3-dab3b1f1a6b9/b2c-jwt-token-signature-validation?forum=WindowsAzureAD&prof=required

And in one of those comments, there's a broken link to `OpenIdConnectCachingSecurityTokenProvider` .  After digging around a bit, I found this discussion:

https://github.com/AzureADQuickStarts/B2C-WebApp-WebAPI-OpenIDConnect-DotNet/issues/2

Dig around in that repo and I think you'll find the class from the broken link.

As you can see, I'm out of my depth here.  So I ended up taking the server based approach because I found myself getting sucked in way over my head and I've learned to **read and reread whatever Adrian says and just do that.**

**Comment by adrianhall** [comment]
Client-directed logins can’t work unless B2C supports access tokens.  When we first introduced our B2C integration, B2C did not issue access tokens. I think this is why we said the client flow was not supported. Is that no longer the case? I ran my test app just now and I get an id_token and a refresh_token when logging in, but no access_token.
 
The most recent docs seem to indicate that clients can acquire access_tokens from B2C now. If that’s the case, then I think client-directed auth (via MSAL) can be made to work with App Service. However, we’ve not tested this so there may be some work required on our side to ensure proper functionality.

**Comment by adrianhall** [comment]
And, obviously, if someone wants to provide code snippets, I'm happy to add their contributions to the book :-)

**Comment by adrianhall** [comment]
http://simonjaeger.com/microsoft-authentication-library-preview/ - suggested that access_token is retrievable via MSAL, so I'm going to try it out tonight more extensively.  If it works, I'll update the book.

**Comment by adrianhall** [comment]
Based on timelines and input from the teams, it looks like this is going to happen - just not in time for my closing of the book.  As a result, closing this issue.

**Comment by GNMurthy1982** [comment]
Any update on this issue.
Is this got resolved.. can we use ADAL with B2C?

**Comment by adrianhall** [comment]
I have just started doing a revamp of the book, now that I am back at Microsoft and able to work on it again.  Once I deal with identity, I'll work on what the best practice is for B2C as that is a core part of the story.  Watch for the new book!

**Comment by ckarras** [comment]
@adrianhall What book are you referring to? Does it show how ADAL can be used with B2C?

**Comment by Mephisztoe** [comment]
I was just about opening a new thread on this. 

What I am doing is calling MSAL's AcquireTokenSilentAsync, encapsulating the results' accesstoken within a JObject  and calling MobileServiceClients' LoginAsync method with it like this:

```
var response = Task.Run(async () => await App.PCA.AcquireTokenSilentAsync(
    App.Scopes,
    AuthenticationHelper.GetAccountByPolicy(accounts, App.PolicySignUpSignIn),
    App.Authority,
    false));

var zumoPayload = new JObject()
{
    ["access_token"] = response.Result.AccessToken
};

MobileServiceUser user = await App.Client.LoginAsync(
    MobileServiceAuthenticationProvider.WindowsAzureActiveDirectory,
    zumoPayload);
```

Also, I was wondering if - when working on the new book - can you solve the confusion about the deprecated SDKs from Microsoft? Although Azure Mobile Apps is deprecated, Azure Mobile Apps (Client / Server) is not, but there is a lot of naming interference going on here and it's not easy to understand what to use and what not. :)
