### ISSUE TITLE
CHAPTER 5 - iOS App Id

### ISSUE THREAD

**Issue by ericbrunner** [adrianhall/develop-mobile-apps-with-csharp-and-azure#31]
To get push work on iOS you are required to create a unique bundle identifier which is provisioned for APNS push. In the book it is mentioned that you can do that with a Wildcard (*) provisioning profile but that is wrong.

**Comment by ericbrunner** [comment]
I mean you need an Explicite App Id.

**Comment by adrianhall** [comment]
Thanks Eric - when I tested this, I could use a wildcard provisioning profile.  It may be that the rules have changed.  I'll re-verify the process.

**Comment by ericbrunner** [comment]
I read it there in article 1.1 http://pushtry.com/iostutorial.aspx but if itvworks on your side then it must be a wrong information from my side. Let me know if it works then I can ease my certification and provisioning process, too. Thanks.

**Comment by adrianhall** [comment]
Corrected in 77e55b5..65f4693
