### ISSUE TITLE
Using B2C as third party tokens 

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#32]
Trying to combine your suggestion of native SDK with my requirement of B2C.  So I loaded MSAL and I'm working with local accounts only at the moment (I'm aware of the social network IDP issues for now).  It's working great if I don't validate the token.

In this section of your document: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/custom/#using-third-party-tokens you suggest :

`You can do this by acquiring the token secret and using tokenHandler.ValidateToken() instead of tokenHandler.ReadToken().`

You mention obtaining the secret key and I can't seem to find that for B2C tokens.  I actually worked through it all, and I think maybe I need to add the key into the TokenValidationParameters object before calling the ValidateToken method.

But then I stumbled upon references to: OpenIdConnectCachingSecurityTokenProvider, which is apparently part of a MS repo and I certainly don't have the expertise to start carving pieces out of that.

This seems like a pretty large can of worms I'm working hard to open.  Should I just move on and figure this will be cleared up with maturing of B2C, migration of ADAL to MSAL or improved documentation?

Or am I whistling Dixie?

TIA as always.

**Comment by nhwilly** [comment]
Oh, here's what I get back in the exception, if that helps.

`IDX10500: Signature validation failed. Unable to resolve SecurityKeyIdentifier: 'SecurityKeyIdentifier
    (
    IsReadOnly = False,
    Count = 1,
    Clause[0] = System.IdentityModel.Tokens.NamedKeySecurityKeyIdentifierClause
    )
', 
token: '{"typ":"JWT","alg":"RS256","kid":"gfIKIH-yZ3phRH...zPat0CNY4sA"}.{"exp":1485110890,"nbf":1485107290,"ver":"1.0","iss":"https://login.microsoftonline.com/b2c5ab85-1947-4....a76e-073c5c5734b0/v2.0/","sub":"8110e070-371b-49d4-823d-5527113ebabe","aud":"9afd18b5-....b388-172d04d27645","iat":1485107290,"auth_time":1485107290,"oid":"8110e070-371b-49d4-823d-5527113ebabe","tfp":"B2C_1_local.signin"}'.`

**Comment by adrianhall** [comment]
Thanks for the report.  Unfortunately, B2C is still in development, as is MSAL.  I'll do another pass through the whole section and validate the ValidateToken() advice prior to calling the book done.  If it doesn't work, I'll remove it.

**Comment by adrianhall** [comment]
As with your other AAD B2C issue, we can onlywork with server-flow, so this issue is moot right now.
