### ISSUE TITLE
Azure ad B2C policies

### ISSUE THREAD

**Issue by xerotolerant** [adrianhall/develop-mobile-apps-with-csharp-and-azure#34]
I followed the tutorial from chapter 6 in order to connect the a mobile app and a web app. 
I would like to know

How to select different policies on azure AD b2c? I tried changing the loginUrl to
`<authentication mode="Forms">
      <forms loginUrl="/.auth/login/aad?p=B2C_1_SignUpIn" timeout="2880"/>
    </authentication>`

however that does not seem to work. 
I successfully created a policy and I have no problem doing viewing the policy however when I attempt to the login on the site I get redirected to the default policy.

**Comment by adrianhall** [comment]
Unfortunately, you cannot do this right now.  The queries do not get passed on.  You choose the policy based on the metadata endpoint you provide to the App Service Authentication settings - not via your code.

**Comment by adrianhall** [comment]
Found this blog: http://simonjaeger.com/microsoft-authentication-library-preview/ - seems to give me the access_token.  Once I have tried it out successfully, I'll update the book.

**Comment by xerotolerant** [comment]
Thanks for the prompt reply. How would I set the metadata endpoint? According to the insturctions I was t oset the issuerUrl and ClientId in the azure portal to the  
`https://sts.windows.net/******8`

Which I did. how can I change it to point to the policy created? There is nothing matching the format above in the xml file for the policy.
