### ISSUE TITLE
Chapter 2 - Authenticattion not working anymore

### ISSUE THREAD

**Issue by Abhi728** [adrianhall/develop-mobile-apps-with-csharp-and-azure#35]
Hi , 

I followed all the steps from Chapter 2 and came across the following issues . 

In the Users data object :

     using System.ComponentModel.DataAnnotations; 

     [Key]
     public int Id { get; set; }

The [Key] no longer works and is not part of DataAnnotations . I used Users : EntityData  but i'm getting a 500 internal server error now.

             List<User> users = new List<User>
            {
                new User { Id = Guid.NewGuid().ToString(), Username = "adrian", Password = "supersecret" }
            };

            foreach (User user in users)
            {
                context.Set<User>().Add(user);
            }

**Comment by adrianhall** [comment]
You have likely upgraded a package in NuGet to a .NETCore package and shouldn't have.  My guess is Entity Framework.

If that hasn't happened, then file a bug in azure/azure-mobile-apps-net-server - this isn't a good support avenue for the SDK itself.

**Comment by ericbrunner** [comment]
@Abhi728 What you are doing can't work in my opinon. The `Id `in `EntityData `class is already a Primary Key in the Database table. Look at my code sample below:

In your Mobile Apps backend (Server):

      [Table("TruckFahrer", Schema = "dbo")]
       public class TruckFahrer : EntityData
       {

        [Required]
        public int FahrerId { get; set; }

        [StringLength(50)]
        public string FahrerBez { get; set; }

        [StringLength(50)]
        public string FahrerName { get; set; }

. . . 

on the mobile client side:

    public abstract class TableData
    {
        public string Id { get; set; }

        public DateTimeOffset? UpdatedAt { get; set; }

        public DateTimeOffset? CreatedAt { get; set; }

        public string Version { get; set; }
    }

     public class TruckFahrer : TableData
     {
        public int FahrerId { get; set; }

        public string FahrerBez { get; set; }

        public string FahrerName { get; set; }

. . .

Hope it helps
