### ISSUE TITLE
AuthenticationDelegatingHandler receiving 200 instead of 401

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#37]
For background, I'm calling `LoginAsync` with a policy parameter at `https://.../.auth/login/aad` which performs a B2C based login flow and returns a B2C issued token to the client.  Then I call `LoginAsync` at my custom authentication endpoint, whereupon I add all the claims I need and return my own token to the client via the `LoginResult`.

`Authentication/Authorization` on the service is set to `ON` and `Allow...`

Since I'm using custom authentication, I'm also doing a little custom refresh token work as well.  I've got it all working and I'm now working on catching the 401's automatically as you suggest.

This all works great.  I am storing the tokens, per your suggestion.  I want to call my custom refresh authorization endpoint when the app starts up, using the stored token.  

When the client asks my Azure Mobile App backend endpoint to refresh their claims, I check to see if they are still authorized.  The incoming token may still be valid, but I need to update the values - maybe their status has changed, etc.  I was using `LoginAsync` to make these calls.

I altered the test data on the server to have an expired refresh token in order to force a 401 back to the client.  This should restart the authentication flow which is what I wanted.

I tried simply returning `Unauthorized`.  Naturally, the parser is looking for a `LoginResult`, doesn't like that and throws an exception.  Then I made enough changes to call the reauth endpoint using `InvokeApiAsync` instead and manually setting the returned `LoginResult` user and token in the client.  That should run my reauth attempt through the handler.

When I attempt to return a `Unauthorized` (or any other form of a 401) the handler sees a 200.  I am working two debuggers at the same time and stepping through my code.

After much fiddling around, I've discovered that any other response status _other than a 401_ is seen just fine in the handler.  I've tried `BadRequest`, `UpgradeRequired`, `ServiceUnavailable`, etc.  For some reason, a 401 (and only a 401) **always** gets turned into a 200.

I've tried turning [Authorize] on and off on the controller.  

I realize `LoginAsync` has a different authenticating handler designed not to loop on 401's back through the `AuthenticationDelegatingHandler`

Since `LoginAsync` is expecting a `LoginResult`, should I just return a 200 with some other indicator instead of a 401?  Null? It would keep these calls out of the handler.

I'm sure I can work around whatever is happening, I just can't figure out how a 401 becomes a 200.

Sorry to be outside the box.  I seem to live there.

It's referenced this section of the book:  https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/realworld/#using-refresh-tokens

TIA - Bill

**Comment by adrianhall** [comment]
It may be that the client SDK is swallowing the 401 (which it shouldn't in a delegating handler).  Without stepping through the code myself (which I don't have time to do - sorry!), it's hard to say.  When I was doing the authenticationdelegatinghandler work, I could get 401 codes no problem, so I don't think it is a problem in the book (happy to be proven wrong here).

If you do discover it is in the client SDK, then file an issue in the client SDK repo.

**Comment by nhwilly** [comment]
First, thanks for the quick reply.

My primary objective was to make sure I hadn't lost my mind or didn't understand how this was supposed to work.  While your response doesn't disprove either of those, at least I can focus someplace else for now.  :)

I'd be happy to do it, but I am seriously out of my depth trying to step through the client SDK, which I'm not even sure how to do.  It may be that there are other ways to skin this cat and I'll look in that direction.

This all surfaces in my code while I would be attempting a silent refresh in the delegating handler.  If that fails because there's a problem (such as the refresh token being expired), I'll just have to catch it some other way.

**Comment by nhwilly** [comment]
OK, I found the problem.

Apparently when I return an `Unauthorized` from my controller, the service is redirecting me to B2C which is issuing my sign in web page.  That's how I get the 200 response.

It's not from my backend, it's from B2C.

I even tried moving everything back to using `LoginAsync` to remove the handler from the equation.  If I force an `Unauthorized` response on the backend, my response on the client is coming from B2C.

I guess I could look into trying to get my initial token directly from B2C in the client, putting an [Authorize] attribute on all my methods and then doing my custom authentication.  The backend wouldn't redirect anywhere, it'd just return 401's.  But that puts me back in the soup with MSAL/ADAL.

Do you happen to know, is there a simple way to just call a B2C endpoint in a webview and process the results?

**Comment by nhwilly** [comment]
And to make it worse, I was trying to use this to do web as well as native clients and I haven't even gotten to that yet.  >.<

**Comment by nhwilly** [comment]
Found it:  https://docs.microsoft.com/en-us/azure/active-directory-b2c/active-directory-b2c-reference-oidc

**Comment by nhwilly** [comment]
In case this helps anyone looking here, I was trying to share authentication with MVC per this segment in the book:
https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter6/mvc/#sharing-authentication

This entry in the web config file is what is throwing it off.  I removed it an unauthorized requests get return to the client.

     <authentication mode="Forms">
      <forms loginUrl="/.auth/login/aad" timeout="2880"/>
    </authentication>

As I was working through the book examples as the book was being developed, I may have missed a step.  I'll repeat that entire chapter and see what happens.  Maybe I missed something in creating an MVC app and converting it to a Mobile App.
