### ISSUE TITLE
Missing package in MVC section

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#38]
I had a couple of hiccoughs using the Quickstart package, so I just installed the packages one by one.  I learn things the hard way only.

It's important to upgrade to 4.61 framework first.  That makes things go more smoothly.

I installed the packages in the order list, one by one, and in resolving the errors, figured out that `Microsoft.Azure.Mobile.Server.Login` is missing from your list.

At least it didn't get installed by any other package and when I installed it, the missing reference errors went away.

**Comment by adrianhall** [comment]
Thanks - I guess I missed one!

**Comment by adrianhall** [comment]
Fixed in 4b20199 and published.  Thanks fro the report!
