### ISSUE TITLE
Sharing Authentication with MVC sites and Custom Authentication in Mobile Apps

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#39]
`<preface>`
These are the ramblings of a total hack/noob who's out of his depth and truly frustrated by something that seems like it belongs in the MVC documentation.
`</preface>`

**Book section**: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter6/mvc/#sharing-authentication

I recreated the entire mobile app using the MVC first approach to make certain I wasn't missing something important.  Everything works really well, except that my last step of adding the following:

    <authentication mode="Forms">
      <forms loginUrl="/.auth/login/aad" timeout="2880"/>
    </authentication>

to the web config.  This seems to prevent the use of a custom authentication endpoint for mobile clients because it makes it no longer possible to return an unauthorized response to the client.   Take it out and everything is peachy.

I also discovered another closed issue where the problem is similar if not identical. #36 

After two days of research, I've discovered this has been a problem for quite some time as folks making AJAX calls to MVC sites have the exact same problem of wanting a 401 instead of being redirected. 

In .NET 4.5 an additional method `HttpResponse.SuppressFormsAuthenticationRedirect ` was added.  For the life of me, I can't figure out what it does.  I can't get it to have any effect on anything and the documentation is truly nonexistent.  I'm not the only one, there are other examples in SO.

In addition, I tried custom authorization attributes (but those are occurring elsewhere in the pipeline) and a context wrapper class that is supposed to determine if AJAX is being used.  It does, but only because JQuery is putting something in a header and we're not doing JQuery.  I also looked at trying to put api controllers in one folder and web pages in another and then denying access to the api controllers with no redirect instructions, but tabled that as it looked clumsy and prone to problems later.

So I dropped back to some other suggestions, one of which was very similar to what I've pasted below.  This seems to work, but smells a bit and might be brittle.

In the `Global.Asax` file, I've added:

        protected void Application_EndRequest(object sender, EventArgs e)
        {
            HttpApplication context = (HttpApplication)sender;
            if (FormsAuthentication.IsEnabled 
                && context.Response.StatusCode == 302 
                && context.Request.ContentType == "application/json")
            {
                context.Response.StatusCode = 401;
                context.Response.End();
            }
        }

All of the calls coming in from the devices, including LoginAsync as asking for JSON.  Web pages are showing an empty string in the `ContentType`

If I've lost my mind or you feel strongly that this will blow up later, please tell me.  So far it seems to work, but I've been trying to work out all the identity issues before really digging in to my app.

At the very least, some kind of warning in the book in the sharing authorization section on MVC about not working with custom authentication is probably warranted.

As always, I'd be lost without this book and is truly appreciated.

@julianonunes - You might try this and see if it helps you or extend the ideas to something more robust.  G/L

**Comment by adrianhall** [comment]
Agreed - I'll get a warning in there.

**Comment by adrianhall** [comment]
Added warning in 48902f7 and published.  Thaks for the report!
