### ISSUE TITLE
Server error in '/' Application

### ISSUE THREAD

**Issue by xerotolerant** [adrianhall/develop-mobile-apps-with-csharp-and-azure#40]
After following the instructions in chapter 6 authentication works fine using AADB2C. However when attempting to authenticate using a mobile app. (I follow the instructions in chapters 1 and 2) i am getting this error on the mobile app.

Server error in '/' Application
the resource cannot be founc 

Requested URL: /login/aad

I can't really tell why it would work in one place but not the other.

**Comment by adrianhall** [comment]
You are using an old version of the Azure Mobile Services SDK.  The Requested URL should be /.auth/login/aad if you are using the right SDK.

**Comment by xerotolerant** [comment]
As far as I can tell all of my packages in both the mobile app and backend projects are up to date. Is the Azure Mobile Services SDK related to the Microsoft.Azure.Mobile.XX packages?

**Comment by adrianhall** [comment]
You need to add the Microsoft.Azure.Mobile.Client and associated nugets, as we describe in the book.  You added the wrong nugets to your project.

**Comment by xerotolerant** [comment]
Thanks for your prompt replies. I have the Microsoft.Azure.Mobile.Client packages installed and up to date (version 3.1.0) I thought you were referring to the other thing because you said "Azure mobile services SDK" and that is labeled "Azure Mobile Apps SDK" in nuget. This whole apps vs services thing is confusing.

Also I forgot to say that this message comes up after a successful login. So the entire dialog shows correctly.
