### ISSUE TITLE
A suggestion for working with B2C

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#45]
Adrian,  

After a LOT of hair pulling, I finally arrived at something that you may or may not want to pass along in your book.

In a nutshell, I was trying to use the Page UI customization of B2C to make my onboarding and other identity experiences look sharp.  There are, however, a few limitations at the moment.

1. You cannot customize a sign in policy.  Only sign up / sign in policies.
2. You cannot pass a `login_hint` parameter to a sign in policy without losing the company branding feature.
3. The `can't access your account` function on a sign in page handles all user interaction which is great.
4. But a custom UI page has only a `forgot password` link which returns an error code to the client, so that a unique password reset policy can be called.  For web apps, that means changing the AuthenticationFailed methods and Azure Mobile Apps won't let me do that easily (if at all).
5. A sign up / sign in policy doesn't handle a user whose password policy includes a `forceChangePasswordNextLogin=true`. It only works for sign in policies.

So here's what I did and maybe it will help your readers.  Maybe you'll just roll your eyes.

1. I modified the CSS for a sign up / sign in policy, effectively removing the `sign up` link.  Voila - a sign in only policy that can be customized.  In fairness, not my original idea.
2. I modified the CSS on the same policy to remove the `forgot password` link so that a password reset response can never be received.  That solves the flow problem for MVC web pages and I can continue to use Azure Mobile Apps.  I'll simply add a `forgot password` button somewhere in the menu on all clients.
3. When onboarding a new user via an invitation, I use the Graph API to create a user with a temporary password.  When they activate the link, I'll simply take them directly to a sign in only policy which will force them to reset their password before returning to my client.

This seems like a lot of work, but to the credit of the B2C designers, I was able to find my way to get what I needed out of B2C and Azure Mobile Apps.  Maybe this will help someone else.

**Comment by adrianhall** [comment]
Great information.  I don't think this level of detail is appropriate in the book, especially as the B2C team moves forward with later releases - I would need to be perpetually updating the book :-)

**Comment by nhwilly** [comment]
No worries.  It’s just with all the “it works, except” in B2C and MSAL in a “not quite ready” state and, to be honest, the pace of releases and communication from those teams, I just have to move forward.  Others must be in the same boat.

It’s a shame you aren’t managing those teams.  Your responsiveness and thoroughness have been excellent.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10
