### ISSUE TITLE
Chapter 1 (Mac) - App not running in Android emulator

### ISSUE THREAD

**Issue by marthinfreij** [adrianhall/develop-mobile-apps-with-csharp-and-azure#47]
When I try to run the app in the Android emulator, according to [Building the Client for Android](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter1/firstapp_mac/#building-the-client-for-android) on a Mac, the app immediately crashes showing "Unfortunately, TaskList has stopped.".

I solved this issue by right clicking the TaskList.Droid project and selecting Options. In the Android Build section, select the General tab and uncheck "Use Shared Mono Runtime". Then select the Advanced tab and select all supported ABIs except armeabi.

Clean project and rebuild TaskList.Droid project and then run the app in the emulator again. Works.

Not sure if this is the right way to do it, any ideas?

**Comment by adrianhall** [comment]
Hmm - I don't have to do that.  Were you running on an ARM emulator or the x86 emulator?

**Comment by marthinfreij** [comment]
I just tried the x86 emulator.

**Comment by marthinfreij** [comment]
Ok, I reverted my changes and tried the ARM emulator instead. It took forever, but seems to work fine. But I will go with the x86, because it's so much faster.

**Comment by adrianhall** [comment]
Strange.  I don't have that issue - I'll investigate a little bit, and see if there is documentation needing to be added.  Glad you got it working.

**Comment by adrianhall** [comment]
Fixed in 91e103d
