### ISSUE TITLE
Chapter 1 - TaskListViewModel() - RefreshList()

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#5]
`Chapter 1 / Your First App - PC Edition / The Mobile Client / TaskListViewModel`

In the constructor, RefreshList() is not awaited even though it is async.

This may be by design, but the intellisense was suggesting it should be async..

**Comment by adrianhall** [comment]
This is by design.  It's the simplest way to do what;s required.  I introduce a different method in Chapter 2 (implementing an async command then invoking that).

**Comment by nhwilly** [comment]
Sorry, I was just moving through it from top to bottom, in order and typing all the code by hand.  Odd, I know, but it helps me learn.

I keep OneNote open and when something doesn't work (other than my crappy typing skills) I just jot it down.  I'll work through the entire thing before I submit any more.

**Comment by adrianhall** [comment]
There are several places where Intellisense doesn't do the right thing.  Just because Intellisense says it is bad doesn't mean it is.
