### ISSUE TITLE
Updating Packages

### ISSUE THREAD

**Issue by FilippoPedrazzini** [adrianhall/develop-mobile-apps-with-csharp-and-azure#51]
Your book is awesome and i understood lots of things reading it, I have a problem with your code about the mobile app service. When i update the packages it gives me lots of error. How can i solve this problem? Can i use your code version without updating the packages? I am developing a mobile app and i need a simple Backend and all the code and tutorial I found were not updated. If i cant find a solution probably i will use easy tables.

**Comment by adrianhall** [comment]
You should be able to use the code without updating the packages.  If you are just needing a simple backend, then use Easy Tables - that is also compatible.
