### ISSUE TITLE
DB Schema Reset

### ISSUE THREAD

**Issue by FilippoPedrazzini** [adrianhall/develop-mobile-apps-with-csharp-and-azure#59]
Is there a way in order to reset the DB Schema? After the first publish I would like to modify the tables and upload them again, but I don't want to use the Server Explorer, just republish it from scratch.

thanks

**Comment by adrianhall** [comment]
You mean on the server?  

The MobileServiceInitializer is a an Entity Framework thing.  You can read about the options here: http://www.codeguru.com/csharp/article.php/c19999/Understanding-Database-Initializers-in-Entity-Framework-Code-First.htm

If that isn't what you mean, re-open with a better explanation.
