### ISSUE TITLE
Chapter 1 - Client-Flow for Social Providers

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#6]
Not really an issue, but there should probably be a mention that this approach requires the social app to be installed and the emulator/simulators won't let you do that.  Spent a while trying to figure out what I was doing wrong.

On the plus side, this is very straightforward to implement which is great.

Additionally, some consideration might be included on how to make or not make your app SSO compliant.

FWIW, the entire process for getting your iPhone hooked up so you can deploy to a device is insanely convoluted for first time users, so I can see why it might not make it into this document.

And to make it worse, this app launches on the iPhone and promptly dies and VS2015 believes it's been deployed just fine.  So no pointers there from MS or Apple.  And I have no idea what the problems is or where to start searching, other than looking at really useless logs on the device.  I've probably missed a step or three.

**Comment by adrianhall** [comment]
Added a call out about not being able to test client flow for social providers on the simulator / emulator.
