### ISSUE TITLE
DB Links

### ISSUE THREAD

**Issue by FilippoPedrazzini** [adrianhall/develop-mobile-apps-with-csharp-and-azure#60]
Is there a way to link different tables? I have a table RESERVATION who need a ROOM and I have tried in this way
`public class Reservation : EntityData
	{
		public Room RoomName { get; set; }
		public DateTime Date { get; set; }
		public TimeSpan StartingTime { get; set; }
		public TimeSpan EndingTime { get; set; }
	}`

But when I go in the Server Explorer the column RoomName is a Room ID, which I think is right, but when I build the solution it gives me errors.

**Comment by adrianhall** [comment]
This is covered in detail in chapter 3.

Basically, you cannot do a generic foreign key.  There are specific things you can do to loosely couple the models, but in the end you are dealing with separate tables.
