### ISSUE TITLE
iOS Facebook Login

### ISSUE THREAD

**Issue by FilippoPedrazzini** [adrianhall/develop-mobile-apps-with-csharp-and-azure#61]
I have followed exactly what you did for the iOS login, but the app crashes as soon as reach the splash screen, giving me this error:

Terminating app due to uncaught exception 'InvalidOperationException', reason: 'fb-messenger-api is missing from your Info.plist under LSApplicationQueriesSchemes and is required for iOS 9.0'

But I am debugging with my iPhone which has iOS 10. I tried to include the fb-messenger-api in the info.plist, but it gives me the same error.

**Comment by adrianhall** [comment]
Well, the error is with the facebook SDK.  Not a lot to say but "you've not integrated the facebook SDK correctly".  Unfortunately, I don't provide support for the facebook SDK.   I suggest reaching out to them directly.

I'm copy-editing right now, so I'll go through the process within the next week.  If there is an update required, I'll catch it then.
