### ISSUE TITLE
Microsoft.WindowsAzure.MobileServices is used throughout, despite it being deprecated

### ISSUE THREAD

**Issue by fiksen99** [adrianhall/develop-mobile-apps-with-csharp-and-azure#64]
### Where is the problem?

Throughout the book, but as an example there is use of the MobileServiceUser here:
https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/realworld/#using-refresh-tokens

### What is the problem?

Microsoft.WindowsAzure.MobileServices is recommended for social auth, however this package is deprecated.
e.g.

```
using System.Threading.Tasks;
using **Microsoft.WindowsAzure.MobileServices**;

namespace TaskList.Abstractions
{
    public interface ILoginProvider
    {
        MobileServiceUser RetrieveTokenFromSecureStore();

        void StoreTokenInSecureStore(MobileServiceUser user);

        Task<MobileServiceUser> LoginAsync(MobileServiceClient client);
    }
}
```

### Did you get an exception?

Not quite, I believe this package is causing clashes when trying to use HttpClient in my .Net standard project.

### What platform are you compiling for?

Xamarin, android specifically. Also trying to use it in my .NetStandard 1.6 project

### Package Versions

latest

### What did you do?
See mobile services messaging here: https://github.com/Azure/azure-mobile-services

Unfortunately I don't see examples on the new service to enable client side social authentication as we enabled here.

**Comment by adrianhall** [comment]
This is explained in the book.  MobileServices is the legacy name, but a different package is being used - Microsoft.Azure.Mobile.Client.

The examples in chapter 2 are full of client-side social authentication.
