### ISSUE TITLE
Refresh tokens -Custom Authentication 

### ISSUE THREAD

**Issue by vinayhfs** [adrianhall/develop-mobile-apps-with-csharp-and-azure#65]
Is there way to implement Refresh token with Custom Authentication ?  If yes, please guide. 
There are no details on this in book. Please add your comments on this topic also.

**Comment by filoe** [comment]
I've followed this guide: http://bitoftech.net/2014/07/16/enable-oauth-refresh-tokens-angularjs-app-using-asp-net-web-api-2-owin/

**Comment by vinayhfs** [comment]
True but this is for API apps (Web API) . I am looking for refresh token support in Mobile apps as explained in book using Microsoft.Azure.Mobile.Server.Login on server side and using MobileServiceClient on xamarin  app side

**Comment by filoe** [comment]
I'm using it on mobile apps.

**Comment by adrianhall** [comment]
There isn't a straight forward way.  Basically, Azure App Service does not support nor suggest refresh token support for custom auth.  If all you are doing is to do username / password, then I'd suggest integrating Auth0 instead; or switch over to a different service - AWS Mobile Hub, for example.
