### ISSUE TITLE
Paging section - more request than you expect.

### ISSUE THREAD

**Issue by FrancoisM** [adrianhall/develop-mobile-apps-with-csharp-and-azure#7]
I think you're book should explain the requests related to paging as you do in your blog:
https://shellmonger.com/2016/05/02/30-days-of-zumo-v2-azure-mobile-apps-day-15-understanding-offline-sync/

> Why not stop at the third request? We expect this to be a live system. The OData subsystem is allowed to return less than the requested value and will do so for a variety of reasons. For example, it may be configured with a maximum transfer size and the records won’t fit into the transfer buffer. The only sure way of knowing that you have received all the records is to request more and be told there is no more.

Especially from the book you say that /tables/todoitem?$top=1&$skip=0 would return one result. True but it will make at least 2 requests.

**Comment by adrianhall** [comment]
Thanks for the report - and totally agree with you.  The reference I gave, though (with top/skip) will actually only do 1 request.  

I'll update the paging section.

**Comment by FrancoisM** [comment]
You're certainly right about the one request. It's the offline sync that would always do at least 2 requests even though you ask for only one: PullAsync(myId,query) with query = myTable.Where(x =>x.Id == myId).

**Comment by adrianhall** [comment]
Markdown File is updated - needs QA and re-generation, which will happen on the next release.

**Comment by adrianhall** [comment]
Deployed on main site.
