### ISSUE TITLE
Downloading a file, Chapter 4 -Recipes.

### ISSUE THREAD

**Issue by Quico20** [adrianhall/develop-mobile-apps-with-csharp-and-azure#72]
Hello Adrian:

In Chapter 4 of your book the downloading file section of it, I wanted to ask you, since I'm  noob at Azure Mobile Apps.

You caught my attention in two pieces of your book that isnt too clear to me the first one:

you said in your book and I quote:
 "When downloading, you will need to update the GetStorageTokenController method to provide access to files. One possibility is to provide read/write access to the entire container, allowing the mobile device to get a directory listing for browsing."

How could I modify the GetStorageTokenController? I mean the part that I think I can modify is the blobPolicy, by adding this:

var blobPolicy = new SharedAccessBlobPolicy
            {
                SharedAccessStartTime = DateTime.UtcNow.AddMinutes(-5),
                SharedAccessExpiryTime = DateTime.UtcNow.AddMinutes(60),
                Permissions = SharedAccessBlobPermissions.Read 
                            | SharedAccessBlobPermissions.Write
                            | SharedAccessBlobPermissions.Create 
                            |SharedAccessBlobPermissions.List //This is a new line of code.
            };

the next question you publish the downloading file code at your book, but when getting the SasToken from the GetSasTokenAsync() method you modified it with this one in your book GetSasTokenAsync(filename)

obviously It make me think that i should modify the GetSasTokenAsync() method to accept a string parameter but why and how should I modify that method to accept a string in order to get the file that I want.

Hopefully you could answer me this question about your book, also I think you should add to your projects those examples in chapter 4. I had made the uploading file sample work, there is a correction at it in order to commit the file using a progress bar or by uploading blockIds, you have to use a List<string> blockIds and add each blockId to it once it finish you gotta use PutBlockListAsync(blockIds) method. and the file will be store at blobstorage. that the only issue I found when trying to use the progress bar or percent counter.

Hopefully you can answer my questions.
Thanks in advance
Enrique Pinelo

**Comment by adrianhall** [comment]
HI Enrique,

I'm no longer a part of Microsoft, so I can't explain what might happen in the future.  However, the work on the Azure Mobile Apps Files interface has stopped at it has been removed from consideration.  I'm going to be updating the book with that information.  

As a result, you should not be using that interface; instead you need to create your own mechanism for uploading and downloading files.
