### ISSUE TITLE
Chapter 1 - Building the Client for Android

### ISSUE THREAD

**Issue by ianpowell2017** [adrianhall/develop-mobile-apps-with-csharp-and-azure#73]
### Where is the problem?

https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter1/firstapp_pc/#building-the-client-for-android

### What is the problem?
```
protected override void OnCreate(Bundle bundle)
{
    TabLayoutResource = Resource.Layout.Tabbar;
    ToolbarResource = Resource.Layout.Toolbar;
    base.OnCreate(bundle);

    Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();

    global::Xamarin.Forms.Forms.Init(this, bundle);
    LoadApplication(new App());
}
```

*Microsoft.WindowsAzure.MobileServices.CurrentPlatform.Init();*
Getting compile error in VS 2017
Error	CS0122	'CurrentPlatform' is inaccessible due to its protection level	ToDo.Android

**Comment by adrianhall** [comment]
This sounds like a problem with the SDK, and thus is not something the book can assist with.  I suggest reaching out to the Microsoft team.
