### ISSUE TITLE
SQL Error when Updating record with trigger and invalid eTag

### ISSUE THREAD

**Issue by OmnipotentOwl** [adrianhall/develop-mobile-apps-with-csharp-and-azure#76]
### Where is the problem?

https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter3/server/#using-an-existing-sql-table

### What is the problem?

```SQL
CREATE TRIGGER
    [mobile].[TRG_Mobile_TodoItem_Update]
ON
    [mobile].[TodoItems]
INSTEAD OF
    UPDATE
AS BEGIN
    DECLARE @id AS NVARCHAR(255)
    SELECT @id = inserted.id FROM inserted
    DECLARE @itemid AS BIGINT
    SELECT @itemid = [item_id] FROM [mobile].[SysProps_TodoItems] WHERE [id] = @id

    IF UPDATE(UserId) BEGIN
        DECLARE @userid AS NVARCHAR(255)
        SELECT @userid = inserted.UserId FROM inserted
        UPDATE [dbo].[TodoItems] SET [UserId] = @userid WHERE [id] = @itemid
    END
    IF UPDATE(Title) BEGIN
        DECLARE @title AS NVARCHAR(255)
        SELECT @title = inserted.Title FROM inserted
        UPDATE [dbo].[TodoItems] SET [Title] = @title WHERE [id] = @itemid
    END
    IF UPDATE(Complete) BEGIN
        DECLARE @complete AS BIT
        SELECT @complete = inserted.Complete FROM inserted
        UPDATE [dbo].[TodoItems] SET [Complete] = @complete WHERE [id] = @itemid
    END
    IF UPDATE(deleted) BEGIN
        DECLARE @deleted AS BIT
        SELECT @deleted = inserted.deleted FROM inserted
        UPDATE [mobile].[SysProps_TodoItems] SET [deleted] = @deleted WHERE [item_id] = @itemid
    END
END
GO
```

### Did you get an exception?

Message='The operation failed with the following error: 'Cannot insert the value NULL into column 'Item_ID', table 'db.mobile.tableName_SystemProps'; column does not allow nulls. INSERT fails.
The statement has been terminated.'.'

### What platform are you compiling for?

N/A

### Package Versions

Azure Mobile App .Net Server 2.0.0

### What did you do?

When looking at error logs for my Azure Mobile App .Net Server I found that tables that used a view and triggers the interact with the table based on the above architecture were not saving data when the eTag (Version) did not match the table. It looks like the trigger gets called before the server checks the eTag and see if this will cause a conflict. The result was the server reported back to the client an error 400 (Bad Request) and the client did not update the data with the database. This occurs when the client is using offline sync and the version tag is being used to maintain opportunistic concurrency. 

Query Sample:
```SQL
UPDATE [mobile].[tableView]
SET [Resolved] = 'N'
WHERE (([Id] = '4778C44A-353C-4E88-B0F3-74A600E78F46') AND ([Version] = 0x0000000000054112))
SELECT [Version], [UpdatedAt]
FROM [mobile].[tableView]]
WHERE @@ROWCOUNT > 0 AND [Id] = '4778C44A-353C-4E88-B0F3-74A600E78F46'
```

Expected Query Result if conflict:

Version | UpdatedAt
-- | --
  |  

Expected Query Result if not conflict:

Version | UpdatedAt
-- | --
0x0000000000054113 | 10/25/2017 18:33

Presently using the above trigger doesn't seem to allow for the server to detect that the eTag is not valid and so doesn't support offline sync concurrency. I have only tested this as far as the Update trigger as my app does not use the Insert or Delete functions presently.

### Proposed Fix

```SQL
CREATE TRIGGER
    [mobile].[TRG_Mobile_TodoItem_Update]
ON
    [mobile].[TodoItems]
INSTEAD OF
    UPDATE
AS BEGIN
    DECLARE @id AS NVARCHAR(255)
    SELECT @id = inserted.id FROM inserted
    DECLARE @version as timestamp
    SELECT @version = inserted.version FROM inserted
    DECLARE @itemid AS BIGINT
    SELECT @itemid = [item_id] FROM [mobile].[SysProps_TodoItems] WHERE [id] = @id

	IF EXISTS(SELECT 1 FROM [mobile].[SysProps_TodoItems] WHERE [id] = @id AND [version] = @version) BEGIN

		IF UPDATE(UserId) BEGIN
			DECLARE @userid AS NVARCHAR(255)
			SELECT @userid = inserted.UserId FROM inserted
			UPDATE [dbo].[TodoItems] SET [UserId] = @userid WHERE [id] = @itemid
		END
		IF UPDATE(Title) BEGIN
			DECLARE @title AS NVARCHAR(255)
			SELECT @title = inserted.Title FROM inserted
			UPDATE [dbo].[TodoItems] SET [Title] = @title WHERE [id] = @itemid
		END
		IF UPDATE(Complete) BEGIN
			DECLARE @complete AS BIT
			SELECT @complete = inserted.Complete FROM inserted
			UPDATE [dbo].[TodoItems] SET [Complete] = @complete WHERE [id] = @itemid
		END
		IF UPDATE(deleted) BEGIN
			DECLARE @deleted AS BIT
			SELECT @deleted = inserted.deleted FROM inserted
			UPDATE [mobile].[SysProps_TodoItems] SET [deleted] = @deleted WHERE [item_id] = @itemid
		END
	END
END
```

**Comment by adrianhall** [comment]
The error message is fairly clear.  You have defined an item_id in one of the views - it can't be NULL and you have made it NULL.  This is more an SQL question than a question about the book per-se.

**Comment by OmnipotentOwl** [comment]
The item_id is the link between the existing table id and the sysprops which contain the guid and other azure mobile app properties. The query is an extract from the logs that Azure Mobile App server is generating on its own. The question is more that the book's trigger doesn't handle the situation where the eTag is not the latest version. If the Azure Mobile App server were interacting with a standard table and not the existing table view then the query would execute properly but when it is interacting with the view it looks like how the Azure Mobile App Server SDK implemented the eTag validation was that it used the database to do the validation with the Where clause having the eTag version in it. When the trigger gets involved it doesn't allow SQL to properly execute the Where clause. The value is null because the Update trigger is executing for an empty query. Based on the documentation in the book it should function but doesn't.

This can be validated by doing the following.

1. Client one pushes an update to the view
2. Client one goes offline
3. Client two pulls the row from the view and pushes an update (changing the eTag) to the view
4. Client one comes online and pushes an update that was processed offline by the client to the view.
5. If the database has your trigger then the update fails with the referenced error message.
