### ISSUE TITLE
Packages are out of date.

### ISSUE THREAD

**Issue by sander1095** [adrianhall/develop-mobile-apps-with-csharp-and-azure#77]
### Where is the problem?

https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/enterprise/
### What is the problem?

I believe the packages are out of date. In the first chapter you tell us to update our packages but when we do this your tutorial cannot be followed anymore. Specifically, client.LoginAsync() requires more than 2 parameters. Some other parts fail to compile or work as well.
### Did you get an exception?

No.
### What platform are you compiling for?
Android/iOS

**Comment by adrianhall** [comment]
Agreed - the contents of this book are frozen at this point.  I am not planning on doing any more work on it.  I'll be glad to accept pull requests for fixes.
