### ISSUE TITLE
Suggestion for a Tip in Chapter Five

### ISSUE THREAD

**Issue by nhwilly** [adrianhall/develop-mobile-apps-with-csharp-and-azure#79]
Adrian,

I've probably read parts of your book four and five times over.   Such a great piece of documentation.

Trying to get a really well done UWP toast format isn't easy to find anywhere.  

I stumbled across [this toast content documentation](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/adaptive-interactive-toasts) using [this Microsoft Nuget package](https://www.nuget.org/packages/Microsoft.Toolkit.Uwp.Notifications/)

Absolutely a great reference and even a toolkit for Intellisense addicts like me.

It would be very helpful as a "tip" in the Windows section for others.

I'm sorry, I don't have any idea, nor do I trust myself to pull a PR and make the change myself or I would have done it.

**Comment by adrianhall** [comment]
Thanks.  I'll take a look at the chapter (it's been a while) and update it.

**Comment by adrianhall** [comment]
Since UWP is not being handled any more, I'm going to close this.
