### ISSUE TITLE
Spelling Error?

### ISSUE THREAD

**Issue by SunnySoldier357** [adrianhall/develop-mobile-apps-with-csharp-and-azure#80]
In Chapter 3, under 'Table Controllers':

"To use "Database First", you first set up the database. Then you create a Model and update the DbContext object. For example, out Example model from before can be represented by the following database schema:"

Shouldn't the word 'out' be 'our?

**Comment by adrianhall** [comment]
Yes, it should - I'll correct and get a revision out.  Thanks!

**Comment by adrianhall** [comment]
Published fix.
