### ISSUE TITLE
Question about logout and client side flow?

### ISSUE THREAD

**Issue by EmilAlipiev** [adrianhall/develop-mobile-apps-with-csharp-and-azure#83]
I have probably went through your great documentation 3 times but I would like to ask you questions,
It seems like you change your sample using AAD even using google and facebook. thats why it is not clear for me. 
I am doing client side flow using native facebook and google sdks. Once i received the token, i would register to azure mobile services as below
```

if (string.IsNullOrEmpty(accessToken))  
                    return await App.Client.LoginAsync(RootView, provider, "myuri");
                else
                {
                    var zumoPayload = new Newtonsoft.Json.Linq.JObject();
                    zumoPayload.Add("access_token", accessToken);

                    var result = await App.Client.LoginAsync(provider, zumoPayload);
                    return result;
                }
```

 question here is when I want to refreshtoken, should i do it using sdk again because token wasnt generated on the server side, does this have to be handled also client sdk and register to azure mobile services? 
the same question goes for logout, does below code enough  or I need to logout also from facebook sdk for example? using  `LoginManager.Instance.Logout(); `

```
 CookieManager.Instance.RemoveAllCookie();
                await .App.Client.LogoutAsync();
```

Last question if I have to do these once on facebook sdk and after doing for azure mobile services? what would be the advantage of azure mobile services beside authorization?

**Comment by adrianhall** [comment]
Unfortunately, I cannot answer questions about the Azure Mobile Apps SDK.  It is no longer under development and Microsoft has abandoned it.  I would recommend moving to something else at this point.  I'm involved with AWS now, so I can speak to AWS AppSync and Amazon Cognito as viable alternatives.
