### ISSUE TITLE
System.InvalidOperationException: 'Multiple actions were found that match the request' on Per-Group filter

### ISSUE THREAD

**Issue by scout208** [adrianhall/develop-mobile-apps-with-csharp-and-azure#86]
Following along in Chapter 3, I'm trying to implement the Per-Group data filter. However, I keep getting this error thrown: 

    System.InvalidOperationException: 'Multiple actions were found the match the request'

whenever I try to call the `Get` endpoint in that controller. I think I've traced the problem to the fact that there are two methods starting with the word "Get" in the controller: `GetGroups` and `GetAllExample`. Was there some workaround for this or some configuration that I'm missing to avoid this error?

**Comment by adrianhall** [comment]
I am currently re-writing the book to take into account the latest features of mobile app development for Azure - stay tuned!  unfortunately, this means I won't be able to look into this.

**Comment by scout208** [comment]
No problem. I'm eagerly awaiting your 2019 edition! The first edition was invaluable in helping me setup my mobile backend. Thank you!
