### ISSUE TITLE
Chapter 3 Concepts

### ISSUE THREAD

**Issue by Quico20** [adrianhall/develop-mobile-apps-with-csharp-and-azure#87]
When I first read your book, in the Chapter 3 at the concepts section you created a TableData abstract class, and it contained four fields, Id, CreatedAt, UpdatedAt and Version.

Now I'm reading it again, but instead of those four fields you just deleted CreatedAt field.

Why?

does the server add CreatedAt automatically as it does with Deleted field?, because you didnt mentioned anything about createdat.

Hopefully you can answer me back.

**Comment by adrianhall** [comment]
I haven't looked at this in a number of years, but I believe you are right that the server (or rather, the SQL service) creates the CreatedAt.
