### ISSUE TITLE
Typo in Ch. 2

### ISSUE THREAD

**Issue by davekats** [adrianhall/develop-mobile-apps-with-csharp-and-azure#92]
Typo [here](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/debugging/#update-your-local-development-environment )

UserAppServiceAuthentication() should be UseAppServiceAuthentication().

Thank you for the excellent guide!  😃

**Comment by adrianhall** [comment]
Thanks for the report.  I'm refreshing the book, so this is a little moot at this point.  However, I'll correct.
