### ISSUE TITLE
Question about group claims

### ISSUE THREAD

**Issue by davekats** [adrianhall/develop-mobile-apps-with-csharp-and-azure#93]
In [this section](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/authorization/#adding-group-claims-to-the-request) you explain how to add security groups to the Azure AD token. When I looked in the portal I did not see any applications listed under app registrations. Can I only add security groups to the Azure AD token if I'm using Azure AD based authentication? I am using social auth through Facebook, so I have only done the configuration steps in the Portal described [here](https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/chapter2/social/#facebook-configuration).

**Comment by adrianhall** [comment]
You can't use groups unless the authentication provider supports them.
