### ISSUE TITLE
Is azure Mobile Apps dead

### ISSUE THREAD

**Issue by abrantie1z** [adrianhall/develop-mobile-apps-with-csharp-and-azure#94]
Sir, From Microsoft documentation, it seems they no longer support azure mobile apps as a backend service but rather cosmos db with appcenter. Do u recommend that because i really liked azure mobile apps

**Comment by leastofthese23** [comment]
Thanks for bringing this up abrantie1z. I'm early on in the book/tutorial and not sure what to do now because the instructions say on Azure to click Web + Mobile, then Mobile App, but there is no Web+Mobile option and searching for Mobile App returns no matching result.

**Comment by abrantie1z** [comment]
Bro, lol. have been there you know. I finally took the pain to learn asp.net core web api , which has way more capabilities than azure mobile app. I recommend that for you.

**Comment by leastofthese23** [comment]
What I'm trying to do is sync/backup data between devices for a Xamarin.Forms app for Android and UWP. Do you have any tutorial you can recommend?

**Comment by scout208** [comment]
> Thanks for bringing this up abrantie1z. I'm early on in the book/tutorial and not sure what to do now because the instructions say on Azure to click Web + Mobile, then Mobile App, but there is no Web+Mobile option and searching for Mobile App returns no matching result.

I think that they have changed the portal a little bit so instead of going and creating a Mobile App Service you now just create a Web App. The options are all the exact same except now you have to choose between code and docker. I think for the purposes of this book you would want to choose code and for the runtime stack choose ASP.NET V4.8. Let me know if that helps.

**Comment by adrianhall** [comment]
I'm refreshing the book.  All the activity is now on GitHub (https://github.com/azure/azure-mobile-apps) and it is still very much alive.  I'm just prepping the tutorials for the official release v5.0.0 with ASP.NET Core.
