### ISSUE TITLE
How to inject Common Service Dependency in TableController

### ISSUE THREAD

**Issue by hanatharesh2712** [adrianhall/develop-mobile-apps-with-csharp-and-azure#96]
I am trying to inject CommonService dependency in TableController as like below and it works fine if I call table controller endpoint like "http://localhost:61558/api/TodoItem".

but, It throws an error when I call the same endpoint using "http://localhost:61558/tables/TodoItem"(Correct way as Mobile App SDK call this URL to sync data)

I inject the service dependency like as below:
```
  private readonly ICommonService _ICommonService;
        public TodoItemController(ICommonService commonService)
        {
            _ICommonService = commonService;
        }
```

**Comment by adrianhall** [comment]
This problem is corrected in the latest SDK - github.com/azure/azure-mobile-apps - which relies on ASP.NET Core.  You can't do it with the ASP.NET Framework version.
